// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKYqiWfVtEhwpKlxZFXENF-p9NG7KDy6U',
    appId: '1:317766462367:web:2fb301b7e762956aa06baa',
    messagingSenderId: '317766462367',
    projectId: 'beyond-6b338',
    authDomain: 'beyond-6b338.firebaseapp.com',
    storageBucket: 'beyond-6b338.firebasestorage.app',
    measurementId: 'G-YYZ7E38RRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9JfHhXKnXUxlQVaBCLD9oPQWZzG6JC9w',
    appId: '1:317766462367:android:935bb865b95cb80ca06baa',
    messagingSenderId: '317766462367',
    projectId: 'beyond-6b338',
    storageBucket: 'beyond-6b338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3iFNUgxStSuYk_yCajkCaNWzQFRtN6Vk',
    appId: '1:317766462367:ios:d3c144429524d33ca06baa',
    messagingSenderId: '317766462367',
    projectId: 'beyond-6b338',
    storageBucket: 'beyond-6b338.firebasestorage.app',
    iosBundleId: 'com.messenger.beyond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3iFNUgxStSuYk_yCajkCaNWzQFRtN6Vk',
    appId: '1:317766462367:ios:d3c144429524d33ca06baa',
    messagingSenderId: '317766462367',
    projectId: 'beyond-6b338',
    storageBucket: 'beyond-6b338.firebasestorage.app',
    iosBundleId: 'com.messenger.beyond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKYqiWfVtEhwpKlxZFXENF-p9NG7KDy6U',
    appId: '1:317766462367:web:3cb103e8ed0ea007a06baa',
    messagingSenderId: '317766462367',
    projectId: 'beyond-6b338',
    authDomain: 'beyond-6b338.firebaseapp.com',
    storageBucket: 'beyond-6b338.firebasestorage.app',
    measurementId: 'G-25JYCSLV81',
  );

}